/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#263143",
        "on-surface-variant": "#434655",
        "surface-container-high": "#dee8ff",
        "background": "#f9f9ff",
        "surface-bright": "#f9f9ff",
        "on-primary": "#ffffff",
        "surface-variant": "#d8e3fb",
        "on-tertiary": "#ffffff",
        "outline": "#737686",
        "on-surface": "#111c2d",
        "on-error-container": "#93000a",
        "tertiary-container": "#6b6e70",
        "surface": "#f9f9ff",
        "on-tertiary-fixed-variant": "#444749",
        "outline-variant": "#c3c6d7",
        "primary": "#004ac6",
        "on-tertiary-container": "#eff1f3",
        "surface-dim": "#cfdaf2",
        "primary-fixed": "#dbe1ff",
        "on-tertiary-fixed": "#191c1e",
        "on-primary-fixed": "#00174b",
        "surface-container-highest": "#d8e3fb",
        "surface-tint": "#0053db",
        "on-error": "#ffffff",
        "on-background": "#111c2d",
        "inverse-on-surface": "#ecf1ff",
        "on-secondary-fixed-variant": "#93000b",
        "tertiary-fixed": "#e0e3e5",
        "primary-container": "#2563eb",
        "on-secondary-container": "#fffbff",
        "on-primary-container": "#eeefff",
        "on-secondary-fixed": "#410002",
        "error-container": "#ffdad6",
        "secondary-container": "#e02928",
        "tertiary-fixed-dim": "#c4c7c9",
        "secondary-fixed": "#ffdad6",
        "on-primary-fixed-variant": "#003ea8",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#525657",
        "inverse-primary": "#b4c5ff",
        "surface-container": "#e7eeff",
        "secondary-fixed-dim": "#ffb4ab",
        "surface-container-low": "#f0f3ff",
        "primary-fixed-dim": "#b4c5ff",
        "error": "#ba1a1a",
        "secondary": "#bb0112",
        "on-secondary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "40px",
        "gutter": "24px",
        "stack-md": "16px",
        "margin-mobile": "16px",
        "stack-lg": "32px",
        "stack-sm": "8px",
        "container-max": "1280px",
      },
      fontFamily: {
        "body-sm": ["var(--font-geist)"],
        "headline-lg": ["var(--font-geist)"],
        "label-md": ["var(--font-geist)"],
        "headline-lg-mobile": ["var(--font-geist)"],
        "headline-xl": ["var(--font-geist)"],
        "body-md": ["var(--font-geist)"],
        "headline-md": ["var(--font-geist)"],
        "body-lg": ["var(--font-geist)"],
        sans: ["var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
};
